<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Blazor-ApexCharts" Version="6.0.2" />
      <PackageReference Include="DotNetEnv" Version="3.1.1" />
      <PackageReference Include="DuckDB.NET.Data.Full" Version="1.1.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.11" />
      <PackageReference Include="MudBlazor" Version="8.15.0" />
      <PackageReference Include="Photino.Blazor" Version="4.0.13" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OpenBudgeteer.Blazor\OpenBudgeteer.Blazor.csproj" />
      <ProjectReference Include="..\OpenBudgeteer.Core.Data.DuckDb.Migrations\OpenBudgeteer.Core.Data.DuckDb.Migrations.csproj" />
      <ProjectReference Include="..\OpenBudgeteer.Core\OpenBudgeteer.Core.csproj" />
      <ProjectReference Include="..\OpenBudgeteer.Core.Data.MySql.Migrations\OpenBudgeteer.Core.Data.MySql.Migrations.csproj" />
      <ProjectReference Include="..\OpenBudgeteer.Core.Data.Postgres.Migrations\OpenBudgeteer.Core.Data.Postgres.Migrations.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="wwwroot\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
