<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="DuckDB.NET.Data.Full" Version="1.1.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OpenBudgeteer.Core.Data.Entities\OpenBudgeteer.Core.Data.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="20251205000000_InitialCreate.sql" />
    </ItemGroup>

</Project>