name: Docker Image (arm64)

on:
  push:
    branches: [ docker-build-multiarch ]

env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
          
#      - name: Build Docker image
#        run: docker build . -t "axelander/openbudgeteer:pre-release" -f "OpenBudgeteer.Blazor/Dockerfile"

#      - name: Push Docker image
#        run: docker push axelander/openbudgeteer:pre-release
